# Generated by Django 3.2.13 on 2022-10-21 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('game_name', models.IntegerField(choices=[(1, '덕몽어스'), (2, '리그 오브 레전드'), (3, '오버워치2'), (4, '어몽어스'), (5, '로스트 아크'), (6, '메이플스토리'), (7, '폴가이즈')])),
                ('member', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
