# Generated by Django 3.2.13 on 2022-10-21 06:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='header_tag',
            field=models.IntegerField(choices=[(1, '모집합니다'), (2, '참여합니다')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='join_member',
            field=models.ManyToManyField(related_name='join', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='member',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
