# Generated by Django 3.2.13 on 2022-10-24 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221021_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='header_tag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='member',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
