# Generated by Django 3.2.13 on 2022-10-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221024_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game_name',
            field=models.IntegerField(choices=[(1, '덕몽어스'), (2, '리그 오브 레전드'), (3, '오버워치2'), (4, '어몽어스'), (5, '폴가이즈')]),
        ),
    ]
